config/routes.rb
Bible::Application.routes.draw do

  match "passages/thisweek" => "passages#thisweek"
  match "passages/thismonth" => "passages#thismonth"
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "profile" => "users#edit"

  resources :user_sessions
  resources :users
  resources :passages

  root :to => "passages#index"

end

app/models/passage.rb
# == Schema Information
#
# Table name: passages
#
#  id             :integer          not null, primary key
#  discovery      :date
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#  reference      :string(255)
#  text           :string(255)
#

require 'rubygems'
require 'rest-client'

class Passage < ActiveRecord::Base
  has_many :verses
  belongs_to :user

# Don't do this for fields in teh DB. This will shortcircuit setting fields in the db.
#  attr_accessor :reference, :text, :doc, :discovery

  def user_reference=(ref)
    #self.update_attribute 'user_reference', ref # infinite loop, must call this setter
    write_attribute(:user_reference, ref)
    fetch
  end

  def fetch
    # should this be auto called when the user_reference field is set? why not for now 
    puts "fetch called on passage id #{id}: #{user_reference}"
    @api ||= Esvapi.new
    @api.query user_reference
    self.text = parse @api.massage_query_results
    self.save
  end

  def belongs_to_user(user)
    user.id == self.user_id
  end

  private
  def parse(results)
    self.reference = results[:reference]
    text = [] # could probably use inject here
    results[:verses].each do |verse|
      v = Verse.new
      v.chapter = verse[:chapter]
      v.number = verse[:number]
      v.text = verse[:text]
      text << v.text
    end
    text.join(" ")
  end

end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_filter :require_user

  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.find(
      :all, 
      :conditions => ["user_id = ?", current_user.id], 
      :order => "discovery DESC")
    @range = :all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passages }
    end
  end

  def thisweek
    @one_week_ago = 1.week.ago.to_date
    @passages = Passage.find(:all,
      :conditions => ["discovery >= :discovery AND user_id = :user_id", 
                      :discovery => @one_week_ago, 
                      :user_id => current_user.id],
      :order => "discovery DESC")
    @range = :thisweek

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @passages }
    end
  end

  def thismonth
    @one_month_ago = 1.month.ago.to_date
    @passages = Passage.find(
      :all,
      :conditions => ["discovery >= :discovery AND user_id = :user_id", 
                      :discovery => @one_month_ago,
                      :user_id => current_user.id],
      :order => "discovery DESC")
    @range = :thismonth

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @passages }
    end
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
    @passage = Passage.find(params[:id])
    
    unless @passage.belongs_to_user(current_user)
      #flash[:notice] = "The passage could not be found."
      raise ActionController::RoutingError.new('The passage could not be found.')
      #return false
    end

    @passage.fetch unless @passage.text  
    @passage_text = @passage.text

    # rudimentary just displaying passages with identical refs, ideally we'd to any
    # passages that contain the same verses
    @similar =  Passage.where :reference => @passage.reference, :user_id => current_user.id

    # @verses = @passage.verses

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/new
  # GET /passages/new.json
  def new
    @passage = Passage.new
    @passage.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/1/edit
  def edit
    @passage = Passage.find(params[:id])
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(params[:passage])
    @passage.user_id = current_user.id

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render json: @passage, status: :created, location: @passage }
      else
        format.html { render action: "new" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passages/1
  # PUT /passages/1.json
  def update
    @passage = Passage.find(params[:id])

    respond_to do |format|
      if @passage.update_attributes(params[:passage])
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy

    respond_to do |format|
      format.html { redirect_to passages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.haml
= form_for @passage do |f|
  -if @passage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@passage.errors.count, "error")} prohibited this passage from being saved:"
      %ul
        - @passage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :discovery
    = f.date_select :discovery
  .field
    = f.label :user_reference
    = f.text_field :user_reference
      
  .actions
    = f.submit 'Save'

app/views/passages/edit.html.haml
%h1 Editing passage

= render 'form'

= link_to 'Show', @passage
\|
= link_to 'Back', passages_path

app/views/passages/index.html.haml
#page-header
  %h1 Your Verses

#passages-filter
  .navbar
    .navbar-inner
      %a.brand
        %small Filter by
      %ul.nav
        %li{class:@range == :thisweek && "active"}
          %a{:href => '/passages/thisweek'}
            This Week
        %li{class:@range == :thismonth && "active"}
          %a{:href => '/passages/thismonth'}
            This Month
        %li{class:@range == :all && "active"}
          %a{:href => passages_path}
            All Time
      /
        %li
          %form.navbar-search
            %input.search-query{:type => "text"}
            %button.btn{:type => "submit"}
              Search

= link_to 'New Passage', new_passage_path

%table
  
  - previous = nil
  - @passages.each do |passage|
    - if passage.discovery != previous 
      %tr
        %th{:colspan => 4}= passage.discovery.strftime("%B %-d, %Y, %A")
        - previous = passage.discovery
    %tr
      %td= link_to 'X', passage, :confirm => 'Are you sure?', :method => :delete, :class => 'delete', :title => 'Delete this passage'
      /%td= passage.discovery
      %td.nowrap= link_to passage.reference, passage
      %td= passage.text

%br

app/views/passages/new.html.haml
%h1 New passage

= render 'form'

= link_to 'Back', passages_path

app/views/passages/show.html.haml
- if notice
  %p#notice.alert-success= notice

%h1= @passage.reference

%p= @passage_text

%h3 Dates:
-#%p= @passage.discovery.to_s(:long)

- @similar.each do |passage|
  %p= passage.discovery.to_s(:long)


= link_to 'Edit', edit_passage_path(@passage)
\|
= link_to 'Delete', @passage, :confirm => 'Are you sure?', :method => :delete
\|
= link_to 'Back', passages_path